work_dir: ./work_dir/ntu/xsub/aagcn_joint
model_saved_name: ./runs/ntu_cs_aagcn_joint

train_datasets:
  data_path: /home/nas/user/minseok/skeleton_data/ntu/xsub/train_data_joint.npy
  label_path: /home/nas/user/minseok/skeleton_data/ntu/xsub/train_label.pkl
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

val_datasets:
  data_path: /home/nas/user/minseok/skeleton_data/ntu/xsub/val_data_joint.npy
  label_path: /home/nas/user/minseok/skeleton_data/ntu/xsub/val_label.pkl

dataloader:
  train:
    batch_size: 16 
    shuffle: true
    num_workers: 50

  valid:
    batch_size: 16 
    shuffle: true
    num_workers: 50

  test:
    batch_size: 1
    shuffle: false
    # pin_memeory: true
    num_workers: 50

criterion:
  name: CrossEntropy

optimizer:
  name: Adam
  lr: !!float 1e-3
  # betas: (0.9, 0.999)
  eps: !!float 1e-9
  weight_decay: !!float 1e-2


#### scheduler settings
scheduler:
  name: plateau
  min_lr: !!float 1e-8
  patience: 2
  factor: 0.5


model:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

trainer:
  epochs: 10000
  device: 0 
  save_path: /home/nas/user/minseok/Dacon_final
  #ckpt_path: /home/nas/user/minseok/skeleton/NTU_joint/02February_0253/ckpt/best.pt
  comment: 

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40]
warm_up_epoch: 5

# training
device: [0, 1, 2, 3]
batch_size: 64
test_batch_size: 64
num_epoch: 50
nesterov: True
only_train_part: True
only_train_epoch: 5


